title: "Alex Rivera — Cybersecurity & Backend Developer"
description: "Portfolio showcasing secure backend systems, automation, and case studies."
url: "https://kakradetome.github.io"
baseurl: "/Kay-s-3-Week-Dae-Projects"
theme: jekyll-theme-architect
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md
  - projects.md
  - resume.md
  - contact.md
