theme: minima

header_pages:
    - index.md
    - projects.md

author:
    name: Kay
    email: kay@mydae.org

social_links:
    - { platform: github, user_url: "https://github.com/kakradetome" }
    - {
          platform: linkedin,
          user_url: "https://www.linkedin.com/in/kakradetome/",
      }
