remote_theme: pages-themes/hacker@v0.2.0
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
    - index.md
    - projects.md

author:
    name: Kay
    email: kay@mydae.org

minima:
    social_links:
        - title: Jekyll repository at GitHub
          icon: github
          url: "https://github.com/jekyll/jekyll"
        - title: Jekyll at X (formerly Twitter)
          icon: x-twitter
          url: "https://x.com/jekyllrb"
