title: "YOUR NAME — Cybersecurity & Backend Developer"
description: "Portfolio showcasing secure backend systems, automation, and case studies."
url: "https://kakradetome.github.io"
baseurl: "/Kay-s-3-Week-Dae-Projects"   # must match repo name exactly

theme: minima
permalink: pretty

header_pages:
  - index.md
  - about.md
  - projects.md
  - resume.md
  - contact.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock